### ISSUE TITLE
Automate macOS builds

### ISSUE THREAD

**Issue by nickatsegment** [segmentio/aws-okta#81]
We need a macOS build slave to do it, as we depend on Keychain libs.

**Comment by udondan** [comment]
I assume this is the reason why there currently are no darwin packages available for download since v0.19.3.

I'm trying to provide an installer for our team so we all use the same tooling versions (terraform, terragrunt, awscli, aws-okta,...) 

Via brew only the very latest release is available, so it's not an option.

Is there any reliable source for darwin binaries available?

**Comment by nickatsegment** [comment]
@udondan Yep, we haven't really figured out MacOS binaries for `aws-okta`. Any existing binaries are built on a dev's laptop. We don't really have a huge need at Segment for old builds, so we just use `homebrew` and build from source generally.

You could run your own brew tap.

**Comment by udondan** [comment]
> You could run your own brew tap.

Yeah, this seems to be the best solution. Thanks for your reply. :)
